User auth
pashunt13/samovar pull request #10
Opened 2022-06-18 17:38 UTC by pashunt13

2022-06-18 18:32 UTC, tikijian requested changes

2022-06-18 18:32 UTC, tikijian commented on pages/admin/[id].tsx
> +  async function getServerSideProps(context) {
вот тут можно было бы заюзать деструктуризацию для сокращения доступов к свойствам объекта context
`async function getServerSideProps({ req, query })`

2022-06-18 18:32 UTC, tikijian commented on pages/admin/login.tsx
> +      if (response.status === 200) return (window.location.href = '/admin');
зачем тут скобки в return?

2022-06-18 18:32 UTC, tikijian commented on pages/admin/login.tsx
> +  const [active, setActive] = useState(true);
это используется?

2022-06-18 18:32 UTC, tikijian commented on pages/admin/login.tsx
> +        <div
разве это модалка?

2022-06-18 18:32 UTC, tikijian commented on pages/admin/login.tsx
> +          onClick={(e) => e.stopPropagation()}
шта

2022-06-18 18:32 UTC, tikijian commented on pages/admin/login.tsx
> +          <div className={styles.title}>Войдите, {'\n'}чтобы продолжить</div>
что за  {'\n'} покемон

2022-06-18 18:32 UTC, tikijian commented on pages/admin/login.tsx
> +            <div className={styles.subTitle}>Логин:</div>
по html фен шую для подписей input используют <label>

2022-06-18 18:32 UTC, tikijian commented on pages/admin/[id].tsx
> +  async function getServerSideProps(context) {
еще тут дублирование имени которое уже объявлено (getServerSideProps).
в withIronSessionSsr можно анонимную функцию передать

2022-06-18 18:32 UTC, tikijian commented on pages/admin/[id].tsx
> +    if (!context.req.session.user.authorized) {
если session.user не будет существовать в session и кто то зайдет сюда то будет эксепшн. (сам потести в инкогнито вкладке)

2022-06-18 18:32 UTC, tikijian commented on pages/admin/index.tsx
> +  async function getServerSideProps({ req }) {
дублирование имени которое уже объявлено (getServerSideProps).

2022-06-18 18:32 UTC, tikijian commented on pages/admin/index.tsx
> +    if (!req.session.user.authorized) {
если session.user не будет существовать в session и кто то зайдет сюда то будет эксепшн.

2022-06-18 18:32 UTC, tikijian commented on pages/admin/login.tsx
> +      console.log(login + '  ' + password);
remove

2022-06-18 18:32 UTC, tikijian commented on pages/api/login/index.tsx
> +    res.status(200).json(true);
.json не нужен. Мы там просто статус ответа проверяем

2022-06-18 18:32 UTC, tikijian commented on pages/api/order/index.tsx
> +    console.log(basketItems);
remove

2022-06-19 13:17 UTC, pashunt13 commented on pages/admin/login.tsx
> +      if (response.status === 200) return (window.location.href = '/admin');
prettier шалит

2022-06-19 13:24 UTC, pashunt13 commented on pages/api/login/index.tsx
> +    res.status(200).json(true);
без него не работало почему-то

2022-06-19 20:07 UTC, tikijian approved these changes

2022-06-19 20:19 UTC, merged