Category
pashunt13/samovar pull request #11
Opened 2022-10-29 22:03 UTC by pashunt13

2022-12-12 20:43 UTC, tikijian requested changes

2022-12-12 20:43 UTC, tikijian commented on pages/api/menu/index.tsx
> +    return res.status(200).json(items);
по умолчанию статус и так 200, можно просто res.json(items)

2022-12-12 20:43 UTC, tikijian commented on pages/api/menu/index.tsx
> +  const categoryFilter = req.body;
вообще фильтрацию обычно через GET запросы делают и query параметры

2022-12-12 20:43 UTC, tikijian commented on src/components/Menu/CategoryList.tsx
> +let categoryFilter: number[] = [];
Так не желательно делать. Ты по сути глобальную переменную объявил, которая живет вне контекста компонента. Но по сути является состоянием компонента.
Такому самое место в стейте

2022-12-12 20:43 UTC, tikijian commented on src/components/Menu/CategoryList.tsx
> +    categoryFilter.push(id);
когда перенесешь это в стейт, обновлять надо с помощью setState

2022-12-12 20:43 UTC, tikijian commented on src/components/Menu/CategoryList.tsx
> +  const getNewItems = async () => {
Концептуально такое делают через хук useEffect, который отслеживает изменение стейта (в твоем случае categoryFilter).

```
const getNewItems = useCallback(async () => { .... })

useEffect(() => {
  getNewItems();
}, [categoryFilter]) // тут указываем, где отслеживать изменения
````

Таким образом, каждый раз когда ты будешь менять categoryFilter в removeCategoryHandler и addCategoryHandler  там не нужно будет руками вызывать getNewItems()

2022-12-12 20:43 UTC, tikijian commented on src/components/Menu/CategoryList.tsx
> +      return setItems(data);
не надо везде тулить return, если не подразумевается, что это значение будет использоваться при вызове функции

2022-12-12 20:43 UTC, tikijian commented on src/components/Menu/Category.tsx
> +      onClick={() => categoryHandler(category.id)}
вообще всякие li/div не делают кликабельными. Обычно a или button.

2022-12-14 18:41 UTC, pashunt13 commented on pages/api/menu/index.tsx
> +  const categoryFilter = req.body;
типа вот так, как в удалении было?
![image](https://user-images.githubusercontent.com/87208914/207683369-759b5575-5927-4649-a35e-d0bb8b430d2f.png)
но как я это сделаю, если у меня массив, а там запрос с адресацией типа [id] (query же тут, правильно?)

2022-12-14 21:50 UTC, pashunt13 commented on src/components/Menu/CategoryList.tsx
> +    categoryFilter.push(id);
![image](https://user-images.githubusercontent.com/87208914/207721789-63a331fe-7dd0-4183-af7e-f4a070078125.png)
я вот так сделал, оно работает, но странно - будто скипает первый onClick.
![image](https://user-images.githubusercontent.com/87208914/207722295-9124773c-f67a-49f2-ac53-454feddfe2cd.png)
я конечно еще покопаюсь, но просто дичь, я просто в консоли проверял (скорее всего я чушь понаписал просто)

2022-12-14 21:51 UTC, pashunt13 commented on src/components/Menu/Category.tsx
> +      onClick={() => categoryHandler(category.id)}
ну типа у меня они как список идут внутри <ul>. сделать тогда внутри <li> button? для семантики

2022-12-19 15:58 UTC, tikijian commented on pages/api/menu/index.tsx
> +  const categoryFilter = req.body;
Express умеет превращать query параметры в определенном формате в массив. Поищи

2022-12-19 15:59 UTC, tikijian commented on src/components/Menu/CategoryList.tsx
> +    categoryFilter.push(id);
я даже не понял про что коммент

2022-12-19 16:00 UTC, tikijian commented on src/components/Menu/Category.tsx
> +      onClick={() => categoryHandler(category.id)}
> ну типа у меня они как список идут внутри

Список списком, просто еще button надо вложить. В принципе это не обязательно

2022-12-19 16:01 UTC, tikijian commented on src/components/Menu/CategoryList.tsx
> +    categoryFilter.push(id);
сначала сделай как в комменте про useEffect

2023-07-17 14:32 UTC, merged