Admin
pashunt13/samovar pull request #9
Opened 2022-06-02 23:26 UTC by pashunt13

2022-06-02 23:28 UTC, pashunt13 commented on pages/admin/[id].tsx
> +//   const orderId = Router();
здесь роутер не хочет вызываться - пишет, что работает только в компоненте, то есть с Большой буквы должно называться. попробовал вывести в отдельную функцию, на нарушаются правила хуков

2022-06-02 23:30 UTC, pashunt13 commented on pages/admin/[id].tsx
>      .getMany();
попробовал выводить здесь но выдает такую ошибку и при этом orderId из роутера null. из-за async наверное
![image](https://user-images.githubusercontent.com/87208914/171754767-8b57e107-b353-4f3f-8389-4c890ebabc61.png)

2022-06-03 09:30 UTC, tikijian commented on pages/admin/[id].tsx
>      .getMany();
ну так а чего же ты прямо в реакт компоненте запросы в базу фигачишь, даже без хуков? К базе коннектишься, которая только на бэке существует

2022-06-03 09:30 UTC, tikijian commented on pages/admin/[id].tsx
>      .getMany();
это должно быть в getServerSideProps

2022-06-03 09:35 UTC, tikijian requested changes

2022-06-03 09:35 UTC, tikijian commented on pages/admin/[id].tsx
> +// function Router() {
это отдельно не нужно

2022-06-03 09:35 UTC, tikijian commented on pages/admin/[id].tsx
> +//   const orderId = Router();
Чаще обращайся к документации, а не пиши код наугад "вдруг сработает".
useRouter - это для реакт-компонентов, которые уже в браузере отрабатывают, а для getServerSideProps это не подходит.
вот как надо:

https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props
<img width="893" alt="Снимок экрана 2022-06-03 в 12 31 40" src="https://user-images.githubusercontent.com/1406569/171829339-aa6e91e3-ce27-49b7-a542-773e1e07a9ef.png">

2022-06-04 05:37 UTC, tikijian commented on pages/admin/[id].tsx
> +  const orderId = req.query.id;
ну и как, есть тут id?

2022-06-04 05:41 UTC, tikijian requested changes

2022-06-04 05:41 UTC, tikijian commented on pages/admin/[id].tsx
> +    },
А телефон и емейл пользователя разве не надо на странице заказа показывать?

2022-06-04 14:37 UTC, pashunt13 commented on pages/admin/[id].tsx
> +    },
ну их в общей показывает, там где все ордеры. думаю достаточно будет

2022-06-04 14:37 UTC, pashunt13 commented on pages/admin/[id].tsx
> +  const orderId = req.query.id;
ну вроде как)

2022-06-04 19:01 UTC, tikijian requested changes

2022-06-05 08:24 UTC, tikijian commented on pages/admin/[id].tsx
> +  const handler = async () => {
я про  const handler а не про defaultButtonValue

2022-06-05 09:30 UTC, pashunt13 commented on pages/admin/[id].tsx
> +    .getMany();
но у меня же relations не работало с where, а он мне нужен

2022-06-05 18:07 UTC, tikijian commented on pages/admin/[id].tsx
> +    .getMany();
мы же вроде выяснили, что оно не работало, потому что мы не там код писали

2022-06-09 19:05 UTC, tikijian approved these changes

2022-06-18 05:53 UTC, merged